#!/usr/bin/env bash
# resolve-board-context — SessionStart observation. Every session gets ONE
# stable spelling for the board CLI (ways-of-working audit A1): the resolved
# path as RALPH_BOARD, plus a versionless shim at ~/.ralph/bin/board that
# re-resolves at CALL time, so a release landing mid-session is picked up —
# which is the direction the observed drift demands. Unlike herdr-context.sh
# this is NOT gated on HERDR_ENV: path archaeology is paid by every session,
# not only cockpit-hosted ones. Like every hook here it is NOT enforcement —
# stdout becomes session context (<=3 lines), stderr is dropped by the
# harness, and it NEVER exits non-zero.
set -euo pipefail

# CLAUDE_PLUGIN_ROOT is exported to hook processes; fall back to this script's
# own location (hooks/ and scripts/ are siblings under the plugin root).
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RESOLVER="$PLUGIN_ROOT/scripts/resolve-board.sh"
[ -r "$RESOLVER" ] || exit 0

# The resolver narrates fallbacks on its own stderr; here only the path is
# context. An empty answer means the resolver itself broke — stay silent
# rather than publish a spelling nothing can run.
BOARD_PATH=$(bash "$RESOLVER" 2>/dev/null) || BOARD_PATH=""
[ -n "$BOARD_PATH" ] || exit 0

# Refresh the shim: a tiny exec wrapper, regenerated idempotently via
# write-temp + mv (atomic within the directory) so a concurrent session start
# never reads a half-written file. It embeds the RESOLVER, not the resolved
# path — resolution happens per call, which is the whole point. Best-effort:
# an unwritable HOME loses the shim, never the context line.
SHIM_DIR="${RALPH_BIN_DIR:-$HOME/.ralph/bin}"
SHIM="$SHIM_DIR/board"
SHIM_OK=0
if mkdir -p "$SHIM_DIR" 2>/dev/null; then
  TMP=$(mktemp "$SHIM_DIR/.board.XXXXXX" 2>/dev/null) || TMP=""
  if [ -n "$TMP" ]; then
    printf '#!/usr/bin/env bash\n# Generated by ralph resolve-board-context.sh (SessionStart) — safe to\n# delete; regenerated at the next session start. Re-resolves the newest\n# installed ralph board CLI at every call.\nexec "$(bash %q)" "$@"\n' \
      "$RESOLVER" >"$TMP" 2>/dev/null &&
      chmod +x "$TMP" 2>/dev/null &&
      mv -f "$TMP" "$SHIM" 2>/dev/null &&
      SHIM_OK=1 ||
      rm -f "$TMP" 2>/dev/null || true
  fi
fi
# A shim that failed to land must not be the spelling on line 1 (review on
# #2492): an unwritable HOME would otherwise send every worker at a path that
# does not exist. Fall back to the resolved copy as the one spelling.
[ "$SHIM_OK" -eq 1 ] || { [ -f "$SHIM" ] && [ -x "$SHIM" ]; } || SHIM=""

# Line order is the contract (GH-2490): the shim is the ONE spelling to type.
# Hook stdout becomes session CONTEXT, never environment — measured across 47
# worker sessions, 46 read a leading `RALPH_BOARD=` line as an exported
# variable, ran `"$RALPH_BOARD" get NNN`, and spent 2–5 calls on
# `permission denied` before finding the shim. The resolved path stays on
# line 2 for humans and tests, labelled as what it is.
if [ -n "$SHIM" ]; then
  echo "board CLI: $SHIM <cmd> — the stable path (a shim that re-resolves the newest installed ralph at call time; one allowlistable spelling across releases). Use exactly this spelling."
  echo "RALPH_BOARD=$BOARD_PATH (informational: the copy the shim resolves to right now; NOT exported into your shell — never type \"\$RALPH_BOARD\")"
else
  echo "board CLI: $BOARD_PATH <cmd> — use exactly this spelling (the stable shim could not be written this session)."
  echo "RALPH_BOARD=$BOARD_PATH (informational: NOT exported into your shell — never type \"\$RALPH_BOARD\")"
fi
exit 0
